apiVersion: v1
kind: Namespace
metadata:
  name: bridge
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: administrator
  namespace: bridge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bridge-administrator
subjects:
  - kind: ServiceAccount
    name: administrator
    namespace: bridge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator
  namespace: bridge
  labels:
    app: administrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administrator
  template:
    metadata:
      labels:
        app: administrator
    spec:
      serviceAccountName: administrator
      containers:
        - name: administrator
          image: "{{ADMINISTRATOR_IMAGE}}"
          command: ["bridge", "administrator"]
          env:
            - name: POD_NAMESPACE
              value: bridge
            - name: SERVICE_ACCOUNT_NAME
              value: administrator
            - name: BRIDGE_PROXY_IMAGE
              value: "{{PROXY_IMAGE}}"
          ports:
            - name: grpc
              containerPort: 9090
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: administrator
  namespace: bridge
spec:
  selector:
    app: administrator
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
